### PR TITLE
Add documentation website for Scala 3.0.0

### PR DESCRIPTION
**Pull request by vincenzobaz**
This PR manually adds the content that should have been added automatically when 3.0.0 was released.
It is linked to https://github.com/lampepfl/dotty/pull/12764

### CODE REVIEW

**Comment by vincenzobaz** [comment]
Is it possible to test the content of the PR automatically? I am thinking about urls.
Is it necessary?

**Comment by vincenzobaz** [comment]
@anatoliykmetyuk or @nicolasstucki could you verify this PR?

**Review by julienrf — APPROVED** [review]
Thank you Vincenzo!

I think we should remove the file `CNAME`. It is not clear to me why it was added (but it was not added, when we did the previous 0.x releases…).

**Comment by julienrf** [comment]
@anatoliykmetyuk Is there anything else we should check before merging the PR?

**Review by anatoliykmetyuk — APPROVED** [review]

**Comment by anatoliykmetyuk** [comment]
> @anatoliykmetyuk Is there anything else we should check before merging the PR?
LGTM, let's merge it and see if it works.

**Pull request merged**
