### PR TITLE
Add banner to frozen files

### PR DESCRIPTION
**Pull request by BarkingBad**

### CODE REVIEW

**Comment by BarkingBad** [comment]
obraz

obraz

**Review by julienrf — COMMENTED** [review]
Would it be possible to change the source files of the website, instead of the generated html files? It would be easier to change the banner, if needed.

I am not sure that showing the commit hash is much useful to the readers. Instead, I would just say that the content is not maintained anymore, and up to date documentation can be found at https://docs.scala-lang.org. The link you added to each page might be invalid if at some point we decide to rename things in the repository, so I would just delete that link.

**Comment by BarkingBad** [comment]
> Would it be possible to change the source files of the website, instead of the generated html files? It would be easier to change the banner, if needed.

I can push changes to the branch so the pregenerating banners would be simple `sbt scaladoc/generateScalaDocumentation` task, if this is what you are looking for.

> I am not sure that showing the commit hash is much useful to the readers.

I know it's a little tricky, I wanted to add a link to dotty repo at given revision for "curious" users.

> Instead, I would just say that the content is not maintained anymore, and up to date documentation can be found at https://docs.scala-lang.org. The link you added to each page might be invalid if at some point we decide to rename things in the repository, so I would just delete that link.

Given the fact that there is not yet continuous deployment set up, we cannot guarantee that up-to-date version can be found at `docs.scala-lang` so the banner links to sources of markdown files (which should be up-to-date) and, if the page will be moved to docs.scala-lang via CD, tells the predicted link for that article. However, the main PR with md preprossor is ready and (if only we get markdowns PR merged) the only thing left is adding a gh action for continuous deployment. 
I mean, I know you wanted to experiment with preprocessing/CD, but maybe we should merge this for now so the docs will be at least up-to-date at docs.scala-lang, the banner could go with `... this page is archived ... here is the link at docs.scala-lang ...`, the docs won't diverge anymore, and we could experiment with docs having something already working. 

Or if you don't like the preprocessing we can at least merge md files to the dotty repo and just create pain copy-paste action, but the advantage will be that they will be finally rendered at docs.scala-lang

**Comment by julienrf** [comment]
> I can push changes to the branch so the pregenerating banners would be simple `sbt scaladoc/generateScalaDocumentation` task, if this is what you are looking for.

Yes, but please push them on a separate PR than 13350. I insist that we can’t merge 13350 before we have a frozen website (which means, not overwritten by nightly CI) showing a large banner pointing readers to docs.scala-lang.org.

> I know it's a little tricky, I wanted to add a link to dotty repo at given revision for "curious" users.

OK, maybe you can keep it at the end?

> Given the fact that there is not yet continuous deployment set up, we cannot guarantee that up-to-date version can be found at `docs.scala-lang`

docs.scala-lang.org is already the most up-to-date documentation. What we are trying to do now is to move some content sources back to the dotty repo so that compiler maintainers can update them as they update the compiler.

Most of the changes in the dotty repo are about experimental features, which are … experimental and not widely used, so I think it is acceptable if there is a delay of a few weeks before we update them on docs.scala-lang.org via the continuous deployment set up you are thinking about.

**Comment by BarkingBad** [comment]
> Yes, but please push them on a separate PR than 13350. I insist that we can’t merge 13350 before we have a frozen website (which means, not overwritten by nightly CI) showing a large banner pointing readers to docs.scala-lang.org.

Yes, that's what I meant. 

> docs.scala-lang.org is already the most up-to-date documentation. What we are trying to do now is to move some content sources back to the dotty repo so that compiler maintainers can update them as they update the compiler.

> Most of the changes in the dotty repo are about experimental features, which are … experimental and not widely used, so I think it is acceptable if there is a delay of a few weeks before we update them on docs.scala-lang.org via the continuous deployment set up you are thinking about.

If you say so... I just felt that telling directly that they are up-to-date is a falsehood, since they differ (even though these are small changes, like experimental API etc.)

**Comment by BarkingBad** [comment]
Here is the PR that freezes the site https://github.com/lampepfl/dotty/pull/13550
I think that banners should go then:
for relocated files: `The content of this page has been frozen. Click here (docs.scala-lang link) to find the up to date version of this page.`
for all other files: ` The content of this page has been frozen. You can try to find the file in a raw markdown at lampepfl/dotty`

What do you think?

**Comment by BarkingBad** [comment]
Closing since we probably won't merge it

**Pull request closed without merging**
